
let elements=[
    {sym:'H',name:'Hydrogen',period:1,group:1},
    {sym:'He',name:'Helium',period:1,group:18},
    {sym:'Li',name:'Lithium',period:2,group:1},
    {sym:'Be',name:'Beryllium',period:2,group:2},
    {sym:'B',name:'Boron',period:2,group:13},
    {sym:'C',name:'Carbon',period:2,group:14},
    {sym:'N',name:'Nitrogen',period:2,group:15},
    {sym:'O',name:'Oxygen',period:2,group:16},
    {sym:'F',name:'Fluorine',period:2,group:17},
    {sym:'Ne',name:'Neon',period:2,group:18},
    {sym:'Na',name:'Sodium',period:3,group:1},
    {sym:'Mg',name:'Magnesium',period:3,group:2},
    {sym:'Al',name:'Aluminium',period:3,group:13},
    {sym:'Si',name:'Silion',period:3,group:14},
    {sym:'P',name:'Phosphorous',period:3,group:15},
    {sym:'S',name:'Sulphur',period:3,group:16},
    {sym:'Cl',name:'Chlorine',period:3,group:17},
    {sym:'Ar',name:'Argon',period:3,group:18},
    {sym:'K',name:'Potassium',period:4,group:1},
    {sym:'Ca',name:'Calcium',period:4,group:2},
]
